### ISSUE TITLE
which compiler used?

### ISSUE THREAD

**Issue by brando90** [Ailrun/software_foundations_solution#2]
These don't work
```
# Coq8.4pl6
opam switch
opam switch create coq-8.14pl6 4.07.1
#opam switch create coq-8.14pl6
eval $(opam env --switch=coq-8.14pl6 --set-switch)
opam pin add -y coq 8.14pl6
```

**Comment by brando90** [comment]
doesn't work in mac, above

**Comment by brando90** [comment]
(iit_synthesis) brando9/afs/cs.stanford.edu/u/brando9/software_foundations_solution/book $ opam pin add -y coq 8.14pl6
[ERROR] Package coq has no known version 8.14pl6 in the repositories

**Comment by Ailrun** [comment]
The coq8.4pl6 branch uses 8.4, not 8.14. And the current head uses 8.16.1.
